### ISSUE TITLE
龙书适合什么水平的读者？

### ISSUE THREAD

**Issue by ejacky** [fool2fish/dragon-book-exercise-answers#73]

**Comment by fool2fish** [comment]
这个……个人觉得要逻辑严密，耐心细致最重要，看的过程当中 **一定** 要动手实践，然后最好了解一些操作系统的基础知识，推荐 [深入理解计算机系统](http://book.douban.com/subject/1230413/) 和离散数学

**Comment by ejacky** [comment]
thanks ,  离散数学 有什么好的资料 给推荐的吗？ 只粗略看过一本本科的教材， 印象里是讲集合方面的， 收获没多少。

**Comment by fool2fish** [comment]
离散数学推荐这本：http://book.douban.com/subject/6558200/

龙书前言有详细说明阅读它之前需要掌握些什么知识，你有兴趣可以先看龙书，等遇到问题了再看相关书籍：）
